coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 5%

ignore:
  - "pkg/data/**/*"
  - "**/*_templ.go"
  - "**/*_gen.go"
  - "main.go"
  - "cmd/root.go"
  - "cmd/testdata/**/*"
  - "pkg/wasm/internal/parity/**/*"
