// Code generated by gothicframework — DO NOT EDIT.

package {{.PkgName}}

import (
	. "github.com/felipegenef/gothicframework/v2/pkg/wasm"
{{- if .HasTopics}}
	"github.com/a-h/templ"
	routes "github.com/felipegenef/gothicframework/v2/pkg/helpers/routes"
{{- end}}
{{- if .HasTime}}
	"time"
{{- end}}
)

// ── auto-generated codecs (do not edit) ─────────────────────────────────
{{range .Codecs}}
func _encode_{{.Name}}(v {{.Name}}, e *Encoder) {
{{range .Fields}}	{{.EncLine}}
{{end}}}

func _decode_{{.Name}}(d *Decoder) {{.Name}} {
	var v {{.Name}}
{{range .Fields}}	{{.DecLine}}
{{end}}	return v
}

func _encode_slice{{.Name}}(v []{{.Name}}, e *Encoder) {
	e.U32(uint32(len(v)))
	for _, _item := range v { _encode_{{.Name}}(_item, e) }
}

func _decode_slice{{.Name}}(d *Decoder) []{{.Name}} {
	_n := int(d.U32())
	v := make([]{{.Name}}, _n)
	for _i := range v { v[_i] = _decode_{{.Name}}(d) }
	return v
}
{{end}}
{{range .KeyVars}}var {{.StructName}}Key = BinaryKey("{{.KeyName}}", _encode_{{.StructName}}, _decode_{{.StructName}})

{{end}}
{{range .TopicTypes}}type {{.TypeName}} struct {
{{range .Fields}}	{{.Name}} *ObservableField[{{.Type}}]
{{end}}	_online  bool
	_pending string
}

{{end}}
{{range .ServerFuncs}}func {{.CtorName}}(initial ...{{.StructName}}) *{{.TypeName}} {
	var _z {{.StructName}}
	if len(initial) > 0 { _z = initial[0] }
	return &{{.TypeName}}{
{{range .Fields}}		{{.Name}}: NewObservableField(_z.{{.Name}}),
{{end}}	}
}

func (c *{{.TypeName}}) Set(v {{.StructName}}) {
}

{{end}}
{{- if .HasTopics}}
{{range .MountFns}}func {{.FuncName}}() templ.Component {
	return routes.TopicManagerComponent("{{.WasmName}}", {{.CompressionConst}})
}

{{end}}
{{- end}}
